In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("IMDB.csv")[:20000]
dataset.head()
len(dataset)

20000

In [4]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
nltk.download("stopwords")
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rahulchuchra/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/rahulchuchra/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [5]:
lm=WordNetLemmatizer()
ps=PorterStemmer()
all_stopwords=stopwords.words("english")
all_stopwords.remove("not")

In [6]:
corpus=[]
for i in range(len(dataset)):
    review= re.sub("[^a-zA-Z]"," ",dataset.review[i])
    review=review.lower()
    review=review.split()
    review=[lm.lemmatize(word) for word in review if word not in set(all_stopwords)]
    review=" ".join(review)
    corpus.append(review)

In [7]:
corpus[:10]

['one reviewer mentioned watching oz episode hooked right exactly happened br br first thing struck oz brutality unflinching scene violence set right word go trust not show faint hearted timid show pull punch regard drug sex violence hardcore classic use word br br called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy not high agenda em city home many aryan muslim gangsta latino christian italian irish scuffle death stare dodgy dealing shady agreement never far away br br would say main appeal show due fact go show dare forget pretty picture painted mainstream audience forget charm forget romance oz mess around first episode ever saw struck nasty surreal say ready watched developed taste oz got accustomed high level graphic violence not violence injustice crooked guard sold nickel inmate kill order get away well mannered middle class inmate turned prison bitch due lack street skill 

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [9]:
x=cv.fit_transform(corpus).toarray()
y=dataset.iloc[:,1].values
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([1, 1, 1, ..., 1, 1, 0])

In [9]:
import pickle
import os
bow_path=os.path.join(os.getcwd(),"model.pkl")
# bow_path
pickle.dump(cv,open(bow_path,"wb"))

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(x,y,test_size=0.30,random_state=21)


In [11]:
y_train

array([1, 0, 1, ..., 1, 0, 1])

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
sc = StandardScaler()
mms=MinMaxScaler() #standard scaler provides negative values that do not work in multinomial naive bayes
X_train = sc.fit_transform(X_train)
multi_train=mms.fit_transform(X_train)
X_test = sc.transform(X_test)
multi_test=mms.fit_transform(X_test)

In [19]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [20]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [23]:
clf1.fit(X_train,y_train)
clf2.fit(multi_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [24]:
g_pred=clf1.predict(X_test)
m_pred=clf2.predict(multi_test)
b_pred=clf3.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [28]:
print('GaussianNB ',accuracy_score(y_test,g_pred))
print('MultinomialNB ',accuracy_score(y_test,m_pred))
print('BernoulliNB ',accuracy_score(y_test,b_pred))

GaussianNB  0.6161666666666666
MultinomialNB  0.8341666666666666
BernoulliNB  0.8516666666666667


In [29]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 5,solver="saga",max_iter=120)
classifier.fit(X_train, y_train)

/Users/rahulchuchra/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "


LogisticRegression(max_iter=120, random_state=5, solver='saga')

In [45]:
y_pred=classifier.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
print(cm)
print('Logistic Regression ',score)

[[2589  394]
 [ 417 2600]] 0.8648333333333333


In [34]:
# import joblib
# joblib.dump(classifier,os.path.join(os.getcwd(),"logistic-87.5_solver=saga_max_iter=120"))

['/Users/rahulchuchra/Downloads/DATA SCIENCE/Sentiment_NLP/logistic-87.5_solver=saga_max_iter=120']

In [67]:
from nltk.tokenize import word_tokenize
nltk.download('punkt')
review=input()
review= re.sub("[^a-zA-Z]"," ",review)
review=review.lower()
review=word_tokenize(review)
review=[lm.lemmatize(word) for word in review if word not in set(all_stopwords)]
review=" ".join(review)
l=[]
l.append(review)
cf=pickle.load(open(bow_path,"rb"))
v=cf.transform(l).toarray()
result=classf.predict(v)
result,review,v.any(1)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/rahulchuchra/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


After a flashback, this movie jumps to a couple of slackers, Shaun and Katy, with Shaun proving during a wild bus ride that he is much more than a car attendant. Soon they're on a globe hoping adventure with world-saving dimensions.  The martial arts choreography is terrific, from the opening forest fight through that fantastic bus bit to the final hand-to-hand battle (followed by the big special effects battle seemingly required in every Marvel film). Fights are funny and exciting and that final battle is truly suspenseful.  The cast is also excellent. Awkwafina is as funny as ever, Michelle Yeoh and Tony Leung bring all their seasoned expertise to their roles, and the actors are don't know are also first rate.  Although ... in the case of Simu Liu, who plays Shaun/Shang-Chi, I have no strong opinion. He's a pleasant every man who handles the action scenes well but seems less mythic hero than "genial best friend of the main character." With all the other talent on screen he doesn't ma

(array([1]),
 'flashback movie jump couple slacker shaun katy shaun proving wild bus ride much car attendant soon globe hoping adventure world saving dimension martial art choreography terrific opening forest fight fantastic bus bit final hand hand battle followed big special effect battle seemingly required every marvel film fight funny exciting final battle truly suspenseful cast also excellent awkwafina funny ever michelle yeoh tony leung bring seasoned expertise role actor know also first rate although case simu liu play shaun shang chi strong opinion pleasant every man handle action scene well seems le mythic hero genial best friend main character talent screen manage leave much impression bright side object story fun movie good job mixing humor action tragical reminiscence pace terrific man great fight recommended',
 array([ True]))

True